### ISSUE TITLE
Values coming from a component using a function as a child component are first undefined

### ISSUE THREAD

**Issue by AugustinLF** [Kilix/storybook-addon-jsx#10]
When you use an arrow function at some point of your story, it is at first called with undefined parameters, then with the correct one.

The following example works with a normal `.add('Base')`, or when doing `{option => option && <div key={option.name}>{option.label}</div>}`.

```javascript
const Comp = ({ elements, children }) => (
    <div>
        {elements.map(children)}
    </div>
);
const options = [
    { name: 'register', label: 'Registered' },
    { name: 'done', label: 'Delivered' },
];
export default FelaProvider =>
    storiesOf('Test', module).addWithJSX('Base', () => (
        <Comp elements={options}>
            {option => <div key={option.name}>{option.label}</div>}
        </Comp>
    ));
```

I'm not 100% sure, but I think I also had this problem when using arrow function to declare onChange props, or stuff like that.

**Comment by wcastand** [comment]
We just upgrade storybook-addon-jsx to v3.1.0

Can you test the new version and check if the problem is still present ?
Thanks
