### ISSUE TITLE
Dependency on React 15 prevents clean cutover to React 16

### ISSUE THREAD

**Issue by simon360** [Kilix/storybook-addon-jsx#18]
The `package.json` for `storybook-addon-jsx` has a dependency on `"react": "^15.5.4"`, so it installs its own version of React when the parent project is using React 16.

Is there anything in this addon that's incompatible with React 16? Could the `dependency` on React be changed to a `peerDependency`, and have its range updated to support all the newness?

**Comment by wcastand** [comment]
Hey, sorry for the delay i was on vacation.
I pushed a new version with upgraded dependencies and i passed react and react-dom as peerDependencies.

Let me know if it's good for you :)

**Comment by simon360** [comment]
Looks good to me - thanks!
