### ISSUE TITLE
Props are not all on a new line

### ISSUE THREAD

**Issue by AugustinLF** [Kilix/storybook-addon-jsx#7]
When using a component without children and with several props, the props are not all on a new line, which is against most standards:
```JSX
<Dropdown required={true}
  label='Responsable'
  value={1}
  placeholder='Choisir un responsable' />
```

I would expect something like:
```JSX
<Dropdown
  required={true}
  label='Responsable'
  value={1}
  placeholder='Choisir un responsable'
/>
```

**Comment by alexandrebodin** [comment]
Hi ! 

I opened a PR on the jsx-to-string repo to allow formatting options 

You can follow here https://github.com/grommet/jsx-to-string/issues/24

**Comment by wcastand** [comment]
I changed the formatter to [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string)

So the props should be good for now.
